


# Get All User 
GET  http://localhost:4000/api/users/


# GET A USER BY ID
GET http://localhost:4000/api/users/670655629b1999576ad025ca
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA2NTU2MjliMTk5OTU3NmFkMDI1Y2EiLCJpYXQiOjE3Mjg0Nzc5OTAsImV4cCI6MTcyODQ4MTU5MH0.HzgoRuKHV643VO8Oh28HS4K9rxwDwsCfCi0OlRmu2vk



# Register User
POST http://localhost:4000/api/users/create
Content-Type:application/json

{
    "userName":"ali",
    "email":"al888it@gmail.com",
    "password":"password6789"
}

// Login User 
POST http://localhost:4000/api/users/login
Content-Type:application/json

{
  
    "email":"al888i@gmail.com",
    "password":"password6789"
}


