name: Build Node.js Express backend
on: [push]
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: |
          npm ci
          npm run build --if-present

      - name: Build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  download_artifact:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
