name: Build Node.js Express backend
on: [push]
jobs:
  install_depenencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Depencies
        run: |
          npm ci
          npm run build --if-present

      - name: Build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
