name: Build Node.js Express backend
on: [push]
jobs:
  install_depenencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Depencies
        run: npm ci
